### ISSUE TITLE
Exercise One

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#1]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex1

Create a class User with name and age as its attribute.Instantiate two objects user1 and user2 with some value. Create a method compare that compares the age of user1 and user2. The method should be called in this way: 
user1.compare(user2)
This method should return output like "john is older than mary" or "mary is older than john" based on their age comparison. All Exercises should be submitted by following OOPs.

**Comment by segunadeleye** [comment]
File name must be in lower snake case -> `user.js` in this case.
How about saving the result of the comparison in a variable and returning it once, instead of doing a return in each block.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
Looks good

However, https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex1/user.js#L7 could have been `var result;`
