### ISSUE TITLE
Exercise 11: Matching Numerical Values and Event Propogation

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#11]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex11

Create a form with two text fields labeled "Enter Number" and "Result". When I enter something in first text field and submit the form, it should write true in second text field if entered value is numeric otherwise false. Also if entered value is not numeric, form should not be submitted. Please use only Object oriented approach to write your code.

**Comment by segunadeleye** [comment]
- You have missed a requirement - The form should submit if the input is numeric, otherwise, it should not.
- Decimal numbers are numeric but they return false.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
- If I enter a non-numeric value, false does not show up in the second text box.
- Remove the regex if you are no longer using it.

**Comment by segunadeleye** [comment]
All good.
