### ISSUE TITLE
Exercise 12: Domain/Subdomain Matching

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#12]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex12

Create a simple form with a text field and a submit button. When I enter a URL in this text field and submit the form, it should alert me the domain name from the entered url. For example, If I enter:
http://example.com/folder/file.html, then on submitting the form it should alert something like:
Domain: example.com.

With subdomain: http://vinsol.example.com/folder/file.html, then on submitting the form it should alert something like:
Domain: example.com
Subdomain: vinsol.
Basic Idea is to extract domain name and subdomain from a URL.
Note: Use Regular Expressions for this exercise. Please use only Object oriented approach to write your code.

**Comment by segunadeleye** [comment]
- You are to build the regex yourself.
- You need one regex for the exercise. Read about how to access captured group in regex.
- www.example.com should be a valid URL.
- If I enter http://www.example.com, it should not show www as subdomain. The result should 'Domain: example.com'
- http://www.deal_dey.com/dsds/sdsds returned 'Domain: www.deal'. It should return 'Domain: deal_dey.com'
- http://merchant.deal_dey.com/dsds/sdsds returned 'Domain: deal_dey.com and Subdomain: merchant'

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
Fix the issue with this task as discussed.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
Please fix the issue with this task.
The application sees `www.dealdey.com` and `http://www.dealdey.com` as invalid URLs.

**Comment by damilola-dealdey** [comment]
Fixed.

**Comment by segunadeleye** [comment]
All good
