### ISSUE TITLE
Exercise Two

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#2]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex2

Create a list of checkbox (red, green, yellow, white, black). Now create two links "Check all" and 'None'. When you click on Check All link, all checkboxes will be selected, and when you click on none link all checkboxes will be deselected (working example is gmail).

**Comment by segunadeleye** [comment]
- Use OOP. Similar to what you did in exercise 1
- File name should match class name. For class name of `CheckBox` should be `check_box.js`
- Also watch your indentation

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
If I check any of the checkboxes by clicking it, it doesn't get unchecked whenever I click the 'Uncheck All' button.

**Comment by segunadeleye** [comment]
Looks a lot cleaner now. :+1:
- This can be reduced to just a one-line statement, and I don't mean ternary operator.

```
if (status) {
  boxes[i].checked = true;
} else {
  boxes[i].checked = false;
}
```
- https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex2/toggle_button.js#L10
  https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex2/toggle_button.js#L15 - Check your indentation

**Comment by damilola-dealdey** [comment]
Done.

**Comment by segunadeleye** [comment]
Looks good :100:
