### ISSUE TITLE
Exercise 3: Maximum 3 Checkbox Selected

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#3]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex3

Create a list of checkboxes (Sunday, Monday, Wednesday, Thursday, Tuesday, Friday, Saturday and None). Now when I start checking these checkboxes, it should not let me check more than 3 checkboxes. When I try to check on 4th checkbox it should alert me as "Only 3 days can be selected. You have already selected sunday, monday and tuesday". Now when I click on None, all other checkboxes should be deselected. Also when 'None' is selected and I select any other option (lets assume Sunday), that option (Sunday) will be selected and None will be deselected.

**Comment by segunadeleye** [comment]
Use OOP

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
1. https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex3/day_box.js#L3
   What if you do the selection `this.days = document.querySelectorAll('input.checkbox');` rather than making it an array initially?
2. https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex3/day_box.js#L5
   Move this event attachment part into the `init()` method block.

**Comment by segunadeleye** [comment]
1. https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex3/day_box.js#L7
   https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex3/day_box.js#L8 - Code duplication.
2. Move `this.days = document.querySelectorAll('input.checkbox');` and `this.noneBox = document.getElementById('check-box-none');` into the constructor.
3. https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex3/day_box.js#L1 - Remove the parameter if you do not need it.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
Looks good
