### ISSUE TITLE
Exercise 4: Parent Checkbox and Their Children Checkbox - Movies, Drinks and Bikes

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#4]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex4

Create a div with height 100 and scroll bars. Display a list of checkbox color, drinks, movies and bikes in this div. Now when you click on color checkbox it should display four checkboxes (red, yellow, green, blue) as a child list and color checkbox should be checked with its child list of checkboxes. Again when you click on color checkbox, child list should be hidden and its child checkboxes should get deselected (clear state). Same with movies, drink and bikes.
Movies: [Dar, Sir]
Drinks: [Coke, Pepsi, Dew]
Bikes: [V-rod, Pulsar, CBZ]

Remember: When you click on a parent checkbox and if child list checkboxes are out of visible area the div's scrollbars should scroll and child list should be visible automatically. We should not scroll the div to see them (child list of checkboxes).

**Comment by segunadeleye** [comment]
Use OOP

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
I can see you use a lot of new line in your HTML file. I think you should only use that where necessary. Having a new line after each element does not always make the HTML file more readable than when the new lines are left out. Using too much new lines will only make your file too long.

Also, make the necessary changes to the structure of code based on our discussion

**Comment by damilola-dealdey** [comment]
Empty Lines Removed and Code Redone.

**Comment by segunadeleye** [comment]
Looks good. Just make sure to use the required convention. I am sure you will get used to it with time.
