### ISSUE TITLE
Exercise 5: Dynamic Table - Add Rows, Edit and Delete Existing Rows

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#5]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex5

Create a table. When you click on 'Add new row' button:
It should add a new row in the table.
In the name and email column there will a text field.
In the action column there will be a button save.
When you enter some value in text fields and click save, then:
Values will be saved (if valid). i.e. Name and Email should be present, Email should be a valid email.
Text fields will be replaced by the values entered.
Save button will be replace by Edit / Delete links. You should be able to delete row by clicking on the Delete link, and edit value by clicking on the Edit link.

**Comment by segunadeleye** [comment]
Make the necessary changes to the structure of code based on our discussion.

**Comment by damilola-dealdey** [comment]
Fixed. Please Check.

**Comment by segunadeleye** [comment]
- `name@mail` is not a valid email.
- There is a bug. Clicking the Delete button deletes the row below it. After deleting other rows, the last row can't be deleted.
- Move the `init()` method in the class to the top, just below the constructor, for better readability.
- Why do you have `makeACell`, `makeAButton` and `init` outside the class?
- `Unformify` - use the right convention for this method name.

**Comment by damilola-dealdey** [comment]
Done.

"Why do you have makeACell, makeAButton and init outside the class?"
They are both independent of the class and can serve as utility functions elsewhere.

**Comment by segunadeleye** [comment]
Works fine :100: 
How about moving this part into a method

```
!this.emailField.checkValidity() || !(/(.+)@(.+){2,}\.(.+){2,}/gi.test(this.emailField.value))
```

and the Regex `/(.+)@(.+){2,}\.(.+){2,}/gi` into a variable.
