### ISSUE TITLE
Exercise 6: ( Form Validation Using JS)

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#6]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex6

Create a form like https://www.dropbox.com/s/qccm98brx2hdbrw/Form_validation.png and add JS validations to that form. When you click on 'Go' JS will check all text fields, and give an alert like "Login Id can't be empty". One alert per empty field. For textarea it should check for empty and min length of 50 characters. If any field is invalid then it should not submit the form. Also It should also confirm "Receive Notification"

**Comment by segunadeleye** [comment]
- Follow the specified convention for naming your variables and methods.
- Check indentation
- Move this section into the constructor.

```
  this.loginIdBox = dom.getElementById('loginId');
  this.emailBox = dom.getElementById('email');
  this.nameBox = dom.getElementById('myName');
  this.timezoneBox = dom.getElementById('timezone');
  this.homepageBox = dom.getElementById('homepage');
  this.aboutBox = dom.getElementById('about');
  this.notificationBox = dom.getElementById('notifications');
```
- Is there a need for this `var validator = new Validator();`. Can't we just have `new Validator();`

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
Nice.
