### ISSUE TITLE
Exercise 7: Name Input in Alert and Welcome in Page Content

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#7]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex7

Create an HTML page, when it opens in Browser, it should prompt twice. Once for first name and second for last name. When you enter first and last name, it should alert you as "Hello firstname lastname." After alert, it should put that text in html page.
Note: Keep in mind when you take inputs from users, always consider cases where user has entered null or blank values (few white spaces). User may press ESC button. In such cases you should not accept the input.

**Comment by segunadeleye** [comment]
- Use the required convention.
- Move all functions into the class.
- Refactor code where necessary.

**Comment by damilola-dealdey** [comment]
done

**Comment by segunadeleye** [comment]
Looks good.
However

```
  this.firstname = '';
  this.lastname = '';
```

could have been

```
  this.firstname;
  this.lastname;
```
