### ISSUE TITLE
Exercise 8: Input URL and Open it

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#8]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex8

Write a Script that prompts you for a URL. If the input is an empty url it should alert you. Otherwise it should open that URL in a new window of width 400px and height 450px, without any type of bar (status bar, scroll bars etc..).

**Comment by segunadeleye** [comment]
Use OOP.

**Comment by damilola-dealdey** [comment]
Done. Now OOP.

**Comment by segunadeleye** [comment]
Looks good. However, don't you think `do-while` is more appropriate here https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex8/url.js#L13 ?
