### ISSUE TITLE
Exercise 9: Move countries from one box to the other

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JavaScript-Track#9]
https://github.com/damilola-dealdey/JavaScript-Track/tree/master/Ex9

Create two multiple selection box. First box contains list of countries and when you select a country and click on Add button, selected country will disappear from first box and appear in second box. When you select a country from second box and click on remove button it will disappear from second box and appear in first box

**Comment by segunadeleye** [comment]
- https://github.com/damilola-dealdey/JavaScript-Track/blob/master/Ex9/select.js#L10
  Change this variable name to `_this`.
- Move this section from `init()` into the constructor.

```
  var dom = document;
  this.myBox = dom.getElementById(selectElemId);
  this.transferToBox = dom.getElementById(transferToElemId);
  this.myButton = dom.getElementById(buttonELemId);
```

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
Looks good
